#!/usr/bin/env python3

# The game is simple, all you need to do is figure out the different codes (0~9) and their position generated by game system. When the code is correct and in its position, then the system will give you (1A). If the code is correct but not in the right position, then the system will give you (1B). Game system will tell you how many(1A) or (1B) you got, right after your every guess.

#guess the 3 digit code to defeat the computer!

import random

#first number cant be 0. just how the rules are
firstNumber = random.randint(1,9)

#there will be no repeating numbers to guess so need a while loop
secondNumber = random.randint(0,9)
while firstNumber == secondNumber:
    secondNumber = random.randint(0,9)

#third number cant be the same as first and second number
thirdNumber = random.randint(0,9)
while thirdNumber == firstNumber or thirdNumber == secondNumber:
    thirdNumber = random.randint(0,9)

#testing to see if there are repeats
#testing output as well for easy coding
print(f"{firstNumber} {secondNumber} {thirdNumber}")

keepPlaying = True
A = 0;
B = 0;
X ="X"

while keepPlaying:

    try:
        playerGuessFirstNumber = int(input("Enter first number\n>"))
    except:
        print("Enter a valid first number")

    try:
        playerGuessSecondNumber = int(input("Enter second number\n>"))
    except:
        print("Enter a valid second number")

    try:    
        playerGuessThirdNumber = int(input("Enter third number\n>"))
    except:
        print("Enter a valid third number")



























